# Generated by Django 4.0.7 on 2023-03-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEDIDO REALIZADO', 'Realizado'), ('EM ANDAMENTO', 'Andamento'), ('ENTREGUE', 'Entregue')], default='PEDIDO REALIZADO', max_length=40)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
