# Generated by Django 4.0.7 on 2023-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_avaliable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
