# Generated by Django 4.0.7 on 2023-03-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_buyer'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(related_name='products', through='products.CartProducts', to='carts.cart'),
        ),
    ]
