# Generated by Django 4.0.7 on 2023-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_avaliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
